name: Build Swift Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos

          submodules: recursive

      - name: Install Dependencies
        run: |
          brew install make dpkg ldid
          echo "$(brew --prefix make)/libexec/gnubin" >> "$GITHUB_PATH"

      - name: Build SwiftProtobuf from source
        run: |
    # 克隆并编译
          git clone https://github.com/apple/swift-protobuf.git
          cd swift-protobuf
          swift build -c release
    # 删除 Theos 中原有的 SwiftProtobuf.framework（如果有）
          rm -rf $THEOS/lib/iphone/rootless/SwiftProtobuf.framework
    # 复制新编译的 framework
          cp -r .build/release/SwiftProtobuf.framework $THEOS/lib/iphone/rootless/

     - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: rootless-deb
          path: packages/*.deb
          if-no-files-found: error